root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  source_url: "https://github.com/HimmatMagar/datae/raw/refs/heads/main/archive.zip"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion